/// End-to-end parity test: drives the public `TIPSPipeline.predict(_:)` surface
/// against the same fixture as `ParityTests.swift`, but as a release gate rather
/// than a per-stage debug aid. Tolerances are looser than the per-stage test
/// because we evaluate the full forward pass through the high-level API.
///
/// Reference: upstream PyTorch (`tips.pytorch.image_encoder` /
/// `tips.pytorch.text_encoder`). The fixture is generated by
/// `Tests/generate_parity_fixtures.py` and lives at
/// `Tests/TIPSTests/Fixtures/parity_fixtures.safetensors`.
///
/// The test is skipped (not failed) when the fixture or weights are absent, so
/// CI without weights still passes.
///
/// Tolerances are calibrated to observed Swift-MLX-fp32 vs Torch-fp32-CPU
/// numerics on B14, random seed 42 input:
///
///     [cls_token]        max=3.6e-3  mean=5.5e-4
///     [register_tokens]  max=2.5e-3  mean=5.2e-4
///     [patch_tokens]     max=1.7e-2  mean=1.7e-3
///     [text_embeddings]  max=2.4e-3  mean=3.2e-4
///
///   - `meanAbs` is the bug detector. We hold it ~3x above the observed value
///     so a real porting regression shows up here first.
///   - `maxAbs` absorbs occasional fp32 stragglers (deeper in the patch grid
///     where attention has mixed across more tokens). Per the deliverables
///     doc, the disparity between max and mean is informative.
///
/// To run with weights present:
///   TEST_RUNNER_TIPS_SNAPSHOT_DIR=$HF_CACHE/models--google--tipsv2-b14/snapshots \
///       xcodebuild -scheme mlx-swift-tips -destination 'platform=macOS' \
///       -derivedDataPath .xcdd test \
///       -only-testing:MLXTIPSTests/ParityFixtureTests

import XCTest
import MLX
@testable import MLXTIPS

final class ParityFixtureTests: XCTestCase {

    // Per-output tolerances. Justified in the file header.
    // Image features include patch_tokens which has 786k elements; we set
    // meanAbs ~3x the observed 1.7e-3 to absorb run-to-run variation while
    // staying tight enough to catch a real porting regression.
    private let imageMaxAbs: Float = 5e-2
    private let imageMeanAbs: Float = 5e-3
    private let textMaxAbs: Float = 1e-2
    private let textMeanAbs: Float = 2e-3

    private var fixtures: [String: MLXArray] = [:]
    private var pipeline: TIPSPipeline!

    override func setUpWithError() throws {
        let fixturesURL = URL(fileURLWithPath: #filePath)
            .deletingLastPathComponent()
            .appendingPathComponent("Fixtures/parity_fixtures.safetensors")

        guard FileManager.default.fileExists(atPath: fixturesURL.path) else {
            throw XCTSkip(
                "Fixture not found at \(fixturesURL.path). " +
                "Run `uv run python Tests/generate_parity_fixtures.py` from python/mlx-tips."
            )
        }
        fixtures = try MLX.loadArrays(url: fixturesURL)

        let env = ProcessInfo.processInfo.environment
        let defaultRoot = "~/.cache/huggingface/hub/models--google--tipsv2-b14/snapshots"
        let root = (env["TIPS_SNAPSHOT_DIR"] ?? defaultRoot) as NSString
        let rootURL = URL(fileURLWithPath: root.expandingTildeInPath)

        guard let snap = (try? FileManager.default.contentsOfDirectory(
            at: rootURL,
            includingPropertiesForKeys: [.contentModificationDateKey]
        ))?.max(by: { a, b in
            let da = (try? a.resourceValues(forKeys: [.contentModificationDateKey])
                .contentModificationDate) ?? .distantPast
            let db = (try? b.resourceValues(forKeys: [.contentModificationDateKey])
                .contentModificationDate) ?? .distantPast
            return da < db
        }),
        FileManager.default.fileExists(atPath: snap.appendingPathComponent("model.safetensors").path)
        else {
            throw XCTSkip(
                "Snapshot not found. Set TIPS_SNAPSHOT_DIR (or TEST_RUNNER_TIPS_SNAPSHOT_DIR " +
                "for xcodebuild) to the HF snapshot directory."
            )
        }
        pipeline = try TIPSPipeline.fromPretrained(directory: snap, variant: .B)
    }

    /// Runs the public `predict` surface on the preprocessed tensor stored in
    /// the fixture. We bypass `preprocess(_: CGImage)` here because the fixture
    /// stores the already-preprocessed tensor — so this test isolates the
    /// model + pipeline glue from byte-path differences (CGImage vs PIL).
    func testPipelinePredictParity() throws {
        let pixels = try require("image_input")
        let outputs = pipeline.predict(pixels)

        try assertClose(
            actual: outputs, key: "cls_token",
            atol: imageMaxAbs, meanAtol: imageMeanAbs
        )
        try assertClose(
            actual: outputs, key: "register_tokens",
            atol: imageMaxAbs, meanAtol: imageMeanAbs
        )
        try assertClose(
            actual: outputs, key: "patch_tokens",
            atol: imageMaxAbs, meanAtol: imageMeanAbs
        )
    }

    /// Mirrors the text encoding path of the pipeline's high-level helpers
    /// (`encodeText` / `zeroShotClassify`).
    func testPipelineTextParity() throws {
        let ids = try require("text_ids").asType(.int32)
        let pads = try require("text_paddings").asType(.int32)
        let out = pipeline.model.encodeText(ids: ids, paddings: pads)
        MLX.eval(out)

        try assertClose(
            actual: ["text_embeddings": out], key: "text_embeddings",
            atol: textMaxAbs, meanAtol: textMeanAbs
        )
    }

    // MARK: - Helpers

    private func require(_ key: String) throws -> MLXArray {
        guard let arr = fixtures[key] else {
            throw XCTSkip("Fixture key '\(key)' missing — regenerate fixture.")
        }
        return arr
    }

    /// Assert that `actual[key]` is close to `fixtures["output.<key>"]` under
    /// `(maxAbs, meanAbs)` tolerances, skipping non-finite pairs (per the
    /// release-deliverables convention).
    private func assertClose(
        actual: [String: MLXArray],
        key: String,
        atol: Float,
        meanAtol: Float,
        file: StaticString = #filePath,
        line: UInt = #line
    ) throws {
        guard let a = actual[key] else {
            return XCTFail("missing actual output '\(key)'", file: file, line: line)
        }
        guard let e = fixtures["output.\(key)"] else {
            throw XCTSkip("Fixture key 'output.\(key)' missing — regenerate fixture.")
        }
        let af = a.asType(.float32)
        let ef = e.asType(.float32)
        MLX.eval(af, ef)
        XCTAssertEqual(af.shape, ef.shape, "\(key): shape mismatch", file: file, line: line)

        let aa = af.asArray(Float.self)
        let ee = ef.asArray(Float.self)
        var maxAbs: Float = 0
        var sumAbs: Double = 0
        var n = 0
        for (av, ev) in zip(aa, ee) where av.isFinite && ev.isFinite {
            let d = abs(av - ev)
            if d > maxAbs { maxAbs = d }
            sumAbs += Double(d)
            n += 1
        }
        let meanAbs = Float(sumAbs / Double(max(n, 1)))
        print(String(format: "[%@]  max_abs=%.3e  mean_abs=%.3e  n=%d", key, maxAbs, meanAbs, n))
        if maxAbs > atol || meanAbs > meanAtol {
            XCTFail(
                "\(key): max_abs=\(maxAbs) (atol=\(atol))  mean_abs=\(meanAbs) (meanAtol=\(meanAtol))",
                file: file, line: line
            )
        }
    }
}
